version: 2

preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default

layout:
  /header/:
    -
      - 'menu 30'
      - 'logo-1 40'
      - 'iconnav 30'

  /messages/:
    -
      - message

  /breadcrumbs/:
    -
      - breadcrumbs

  /footer/:
    -
      - 'openinghours 33'
      - 'logo-2 34'
      - 'contact 33'
    -
      - ohschema

  /copyright/:
    - copyright

structure:
  header:
    attributes:
      boxed: '0'
      extra:
        -
          uk-sticky: 'media: 768'
  messages:
    type: section
    attributes:
      boxed: ''
  breadcrumbs:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
content:
  menu:
    attributes:
      menu: main-menu
    block:
      id: sp-hamburger
      variations: align-left
  logo-1:
    attributes:
      text: SnowPage
      class: sp-logo
    block:
      id: sp-logo
      variations: center
  logo-2:
    attributes:
      text: SnowPage
      class: sp-bottom-logo
    block:
      id: sp-bottom-logo
      variations: center
  iconnav:
    title: 'Icon Nav'
    attributes:
      css:
        class: ''
    block:
      id: sp-icons
      variations: align-right
  message:
    attributes:
      message:
        text: 'This is a message to you!'
    block:
      variations: center
  ohschema:
    title: 'Opening Hours Schema.org'
    attributes:
      css:
        class: uk-invisible
    block:
      id: ohschema
      class: uk-invisible
  copyright:
    block:
      variations: 'center nopaddingall nomarginall'
